// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/topascend/go-gf-ueditor/api"
)

type IUEditor interface {
	Action(ctx context.Context, req *api.UEditorReq) (res g.Map, err error)
}

var localUeditor IUEditor

func Ueditor() IUEditor {
	if localUeditor == nil {
		panic("implement not found for interface IUeditor, forgot register?")
	}
	return localUeditor
}

func RegisterUeditor(i IUEditor) {
	localUeditor = i
}
